BUILD_DIR = ./build
DIST_DIR = ./dist
SOURCE_DIR = ./src
RESOURCE_DIR = ./resources
SQL_DIRS = $(sort $(dir $(SQL_FILES)))
UI_FORMS_DIR = $(SOURCE_DIR)/ui/forms

SYS_PYTHON = python3
PYENV = ./.venv
PYENV_BIN = $(PYENV)/bin
PYINSTALLER_FLAGS = -y \
	--name "LibrePlan" \
	--icon=$(RESOURCE_DIR)/icon.png \
	--noconsole \
	--clean \
	--paths $(SOURCE_DIR) \
	--add-data="$(RESOURCE_DIR):resources" \
	--workpath $(BUILD_DIR) \
	--distpath $(DIST_DIR)

ifeq ($(OS), Windows_NT)
SYS_PYTHON = python
PYENV_BIN = $(PYENV)/Scripts
PYINSTALLER_FLAGS := $(subst :,;,$(PYINSTALLER_FLAGS))
endif

PYTHON = $(PYENV_BIN)/python
PIP = $(PYTHON) -m pip
PYINSTALLER = $(PYENV_BIN)/pyinstaller
PYUIC = $(PYENV_BIN)/pyuic5

SQL_FILES := $(shell find $(SOURCE_DIR) -name "*.sql")
SQL_INTERMEDIATE = $(SQL_FILES:.sql=.sql.tmp)
SQL_COMPILED = $(SQL_DIRS:=queries.py)
UI_FORMS = $(wildcard $(UI_FORMS_DIR)/*.ui)
UI_COMPILED = $(UI_FORMS:.ui=.py)

COMPILED_FILES = $(UI_COMPILED) $(SQL_COMPILED)

.PHONY: clean clean-cache clean-venv

.INTERMEDIATE: $(SQL_INTERMEDIATE)

all: exe

setup: $(PYENV) $(COMPILED_FILES)

$(UI_FORMS_DIR)/%.py: $(UI_FORMS_DIR)/%.ui
	$(PYUIC) $< -o $@;

%/queries.py: $(SQL_INTERMEDIATE)
	@echo "# This file is created automatically by the build system." > $@;
	@echo "# DO NOT EDIT THIS FILE DIRECTLY. ALL CHANGES WILL BE LOST." >> $@;
	cat $(shell find $* -name "*.sql.tmp") >> $@;

$(SQL_INTERMEDIATE): %.sql.tmp: %.sql
	@echo > $@;
	echo '$(notdir $*) = """' >> $@;
	@cat $< >> $@;
	@echo '"""' >> $@;

$(PYENV): requirements.txt
	$(SYS_PYTHON) -m venv $(PYENV)
	$(PIP) install -U pip
	$(PIP) install -r requirements.txt

exe: setup
	$(PYINSTALLER) $(PYINSTALLER_FLAGS) $(SOURCE_DIR)/main.py

run: setup
	$(PYTHON) $(SOURCE_DIR)/main.py

clean:
	-rm -rf $(BUILD_DIR) $(DIST_DIR) $(COMPILED_FILES) LibrePlan.spec

clean-cache:
	-find . \( \
		-type d -name .pytest_cache -o -type d -name __pycache__ -o -name "*.pyc" -o -name "*.class" \
	\) -prune -exec rm -rf {} \;

clean-venv:
	-rm -rf $(PYENV)
